-- ============================================================
-- MIGRAÇÃO HERPETOFAUNA — Projeto 165 — C028-2026-04-SC
-- 26 novas espécies + 44 esforços + 108 resultados
-- ============================================================

-- ── PASSO 1: Inserir 26 espécies novas ──
INSERT INTO especies (nome_cientifico, nome_popular, grupo_biologico, reino, filo, classe, ordem,
  familia, genero, autor_e_ano, status_ameaca_global, status_ameaca_nacional, status_copam,
  status_estadual, cites, habito_alimentar, guilda_alimentar, dependencia_florestal,
  endemismo, sensibilidade_ambiental, migratorio, raridade)
VALUES
  ('Amerotyphlops brongersmianus', 'cobra-cega-marrom', 'Herpetofauna', 'Animalia', 'Chordata', 'Reptilia', 'Squamata', 'Typhlopidae', 'Amerotyphlops', 'Vanzolini, 1976', 'LC', NULL, NULL, NULL, NULL, 'Carnívoro', 'Carnívoro', 'Dependente', NULL, 'Média', 'Não', 'Comum'),
  ('Amphisbaena alba', 'cobra-de-duas-cabeças', 'Herpetofauna', 'Animalia', 'Chordata', 'Reptilia', 'Squamata', 'Amphisbaenidae', 'Amphisbaena', 'Linnaeus, 1758', 'LC', NULL, NULL, NULL, NULL, 'Carnívoro', 'Carnívoro', 'Dependente', NULL, 'Média', 'Não', 'Comum'),
  ('Boana pardalis', 'perereca-porco', 'Herpetofauna', 'Animalia', 'Chordata', 'Amphibia', 'Anura', 'Hylidae', 'Boana', 'Spix, 1824', 'LC', NULL, NULL, NULL, NULL, 'Insetívoro', 'Insetívoro', 'Semi-dependente', NULL, 'Média', 'Não', 'Comum'),
  ('Boana faber', 'perereca-martelo', 'Herpetofauna', 'Animalia', 'Chordata', 'Amphibia', 'Anura', 'Hylidae', 'Boana', 'Wied, 1821', 'LC', NULL, NULL, NULL, NULL, 'Insetívoro', 'Insetívoro', 'Semi-dependente', NULL, 'Baixa', 'Não', 'Comum'),
  ('Boana polytaenia', 'perereca-de-pijama', 'Herpetofauna', 'Animalia', 'Chordata', 'Amphibia', 'Anura', 'Hylidae', 'Boana', 'Wied, 1821', 'LC', NULL, NULL, NULL, NULL, 'Insetívoro', 'Insetívoro', 'Semi-dependente', 'Brasil', 'Média', 'Não', 'Comum'),
  ('Crotalus durissus', 'cascavel', 'Herpetofauna', 'Animalia', 'Chordata', 'Reptilia', 'Squamata', 'Viperidae', 'Crotalus', 'Linnaeus, 1758', 'LC', NULL, NULL, NULL, NULL, 'Carnívoro', 'Carnívoro', 'Independente', NULL, 'Média', 'Não', 'Comum'),
  ('Dendropsophus branneri', 'pererequinha-amarela', 'Herpetofauna', 'Animalia', 'Chordata', 'Amphibia', 'Anura', 'Hylidae', 'Dendropsophus', 'Cope, 1870', 'LC', NULL, NULL, NULL, NULL, 'Insetívoro', 'Insetívoro', 'Semi-dependente', 'Brasil', 'Média', 'Não', 'Comum'),
  ('Dendropsophus decipiens', 'pererequinha', 'Herpetofauna', 'Animalia', 'Chordata', 'Amphibia', 'Anura', 'Hylidae', 'Dendropsophus', 'Lutz, 1925', 'LC', NULL, NULL, NULL, NULL, 'Insetívoro', 'Insetívoro', 'Dependente', 'Brasil', 'Alta', 'Não', 'Comum'),
  ('Dendropsophus elegans', 'perereca-de-moldura', 'Herpetofauna', 'Animalia', 'Chordata', 'Amphibia', 'Anura', 'Hylidae', 'Dendropsophus', 'Wied, 1824', 'LC', NULL, NULL, NULL, NULL, 'Insetívoro', 'Insetívoro', 'Semi-dependente', 'Mata Atlântica', 'Média', 'Não', 'Comum'),
  ('Dendropsophus minutus', 'perereca-ampulheta', 'Herpetofauna', 'Animalia', 'Chordata', 'Amphibia', 'Anura', 'Hylidae', 'Dendropsophus', 'Peters, 1872', 'LC', NULL, NULL, NULL, NULL, 'Insetívoro', 'Insetívoro', 'Semi-dependente', NULL, 'Baixa', 'Não', 'Comum'),
  ('Enyalius bilineatus', 'papa-vento', 'Herpetofauna', 'Animalia', 'Chordata', 'Reptilia', 'Squamata', 'Leiosauridae', 'Enyalius', 'Duméril & Bibron, 1837', 'LC', NULL, NULL, NULL, NULL, 'Carnívoro', 'Carnívoro', 'Dependente', NULL, 'Média', 'Não', 'Comum'),
  ('Erythrolamprus typhlus', 'corredeira-verde', 'Herpetofauna', 'Animalia', 'Chordata', 'Reptilia', 'Squamata', 'Dipsadidae', 'Erythrolamprus', 'Linnaeus, 1758', 'LC', NULL, NULL, NULL, NULL, 'Carnívoro', 'Carnívoro', 'Dependente', NULL, 'Média', 'Não', 'Comum'),
  ('Haddadus binotatus', 'rã-da-mata', 'Herpetofauna', 'Animalia', 'Chordata', 'Amphibia', 'Anura', 'Craugastoridae', 'Haddadus', 'Spix, 1824', 'LC', NULL, NULL, NULL, NULL, 'Insetívoro', 'Insetívoro', 'Dependente', NULL, 'Média', 'Não', 'Comum'),
  ('Hylodes cf. uai', 'rã-do-riacho', 'Herpetofauna', 'Animalia', 'Chordata', 'Amphibia', 'Anura', 'Hylodidae', 'Hylodes', NULL, NULL, NULL, NULL, NULL, NULL, 'Insetívoro', 'Insetívoro', 'Dependente', NULL, 'Média', 'Não', 'Comum'),
  ('Leptodactylus fuscus', 'rã-assobiadora', 'Herpetofauna', 'Animalia', 'Chordata', 'Amphibia', 'Anura', 'Leptodactylidae', 'Leptodactylus', 'Schneider, 1799', 'LC', NULL, NULL, NULL, NULL, 'Insetívoro', 'Insetívoro', 'Semi-dependente', NULL, 'Baixa', 'Não', 'Comum'),
  ('Leptodactylus labyrinthicus', 'rã-pimenta', 'Herpetofauna', 'Animalia', 'Chordata', 'Amphibia', 'Anura', 'Leptodactylidae', 'Leptodactylus', 'Spix, 1824', 'LC', NULL, NULL, NULL, NULL, 'Insetívoro', 'Insetívoro', 'Semi-dependente', NULL, 'Baixa', 'Não', 'Comum'),
  ('Leptodactylus luctator', 'rã-manteiga', 'Herpetofauna', 'Animalia', 'Chordata', 'Amphibia', 'Anura', 'Leptodactylidae', 'Leptodactylus', 'Hudson, 1892', 'LC', NULL, NULL, NULL, NULL, 'Insetívoro', 'Insetívoro', 'Semi-dependente', NULL, 'Baixa', 'Não', 'Comum'),
  ('Leptodactylus mystacinus', 'rã-assobiadora', 'Herpetofauna', 'Animalia', 'Chordata', 'Amphibia', 'Anura', 'Leptodactylidae', 'Leptodactylus', 'Burmeister, 1861', 'LC', NULL, NULL, NULL, NULL, 'Insetívoro', 'Insetívoro', 'Dependente', NULL, 'Média', 'Não', 'Comum'),
  ('Ololygon carnevallii', 'perereca', 'Herpetofauna', 'Animalia', 'Chordata', 'Amphibia', 'Anura', 'Hylidae', 'Ololygon', 'C aramaschi & K isteumacher', 'LC', NULL, NULL, NULL, NULL, 'Insetívoro', 'Insetívoro', 'Dependente', 'Minas Gerais', 'Média', 'Não', 'Comum'),
  ('Physalaemus cuvieri', 'rã-cachorro', 'Herpetofauna', 'Animalia', 'Chordata', 'Amphibia', 'Anura', 'Leptodactylidae', 'Physalaemus', 'Fitzinger, 1826', 'LC', NULL, NULL, NULL, NULL, 'Insetívoro', 'Insetívoro', 'Independente', NULL, 'Baixa', 'Não', 'Comum'),
  ('Rhinella crucifer', 'sapo-cururu', 'Herpetofauna', 'Animalia', 'Chordata', 'Amphibia', 'Anura', 'Bufonidae', 'Rhinella', 'Wied-Neuwied, 1821', 'LC', NULL, NULL, NULL, NULL, 'Insetívoro', 'Insetívoro', 'Independente', 'Brasil', 'Baixa', 'Não', 'Comum'),
  ('Rhinella granulosa', 'sapo-cururuzinho', 'Herpetofauna', 'Animalia', 'Chordata', 'Amphibia', 'Anura', 'Bufonidae', 'Rhinella', 'Spix, 1824', 'LC', NULL, NULL, NULL, NULL, 'Insetívoro', 'Insetívoro', 'Semi-dependente', 'Brasil', 'Média', 'Não', 'Comum'),
  ('Scinax aff. perereca', 'raspa-cuíca', 'Herpetofauna', 'Animalia', 'Chordata', 'Amphibia', 'Anura', 'Hylidae', 'Scinax', NULL, NULL, NULL, NULL, NULL, NULL, 'Insetívoro', 'Insetívoro', 'Semi-dependente', NULL, 'Baixa', 'Não', 'Comum'),
  ('Scinax crospedospilus', 'perereca', 'Herpetofauna', 'Animalia', 'Chordata', 'Amphibia', 'Anura', 'Hylidae', 'Scinax', 'Lutz, 1925', 'LC', NULL, NULL, NULL, NULL, 'Insetívoro', 'Insetívoro', 'Dependente', 'Mata Atlântica', 'Média', 'Não', 'Comum'),
  ('Scinax fuscovarius', 'perereca-de-banheiro', 'Herpetofauna', 'Animalia', 'Chordata', 'Amphibia', 'Anura', 'Hylidae', 'Scinax', 'Lutz, 1925', 'LC', NULL, NULL, NULL, NULL, 'Insetívoro', 'Insetívoro', 'Semi-dependente', NULL, 'Baixa', 'Não', 'Comum'),
  ('Tropidurus gr. torquatus', 'calango', 'Herpetofauna', 'Animalia', 'Chordata', 'Reptilia', 'Squamata', 'Tropiduridae', 'Tropidurus', NULL, NULL, NULL, NULL, NULL, NULL, 'Onívoro', 'Onívoro', 'Independente', 'Mata Atlântica', 'Baixa', 'Não', 'Comum')
ON CONFLICT (nome_cientifico) DO NOTHING;

-- ── PASSO 2: Inserir 44 esforços de amostragem ──
INSERT INTO esforcos_amostragem (id_ponto_coleta, grupo_biologico, metodo_de_captura, tipo_de_amostragem, esforco, unidade_esforco)
VALUES
  (45712, 'Herpetofauna', 'Pitfall', 'Quantitativa', 60.0, 'baldes/noite'),
  (45722, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45723, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45724, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45725, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45726, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45727, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45728, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45714, 'Herpetofauna', 'Pitfall', 'Quantitativa', 60.0, 'baldes/noite'),
  (45715, 'Herpetofauna', 'Pitfall', 'Quantitativa', 60.0, 'baldes/noite'),
  (45729, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45730, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45731, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45732, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45733, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45734, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45735, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45716, 'Herpetofauna', 'Pitfall', 'Quantitativa', 60.0, 'baldes/noite'),
  (45717, 'Herpetofauna', 'Pitfall', 'Quantitativa', 60.0, 'baldes/noite'),
  (45736, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45737, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45738, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45739, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45740, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45741, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45742, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45720, 'Herpetofauna', 'Pitfall', 'Quantitativa', 60.0, 'baldes/noite'),
  (45721, 'Herpetofauna', 'Pitfall', 'Quantitativa', 60.0, 'baldes/noite'),
  (45750, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45751, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45752, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45753, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45754, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45755, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45756, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45718, 'Herpetofauna', 'Pitfall', 'Quantitativa', 60.0, 'baldes/noite'),
  (45719, 'Herpetofauna', 'Pitfall', 'Quantitativa', 60.0, 'baldes/noite'),
  (45743, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45744, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45745, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45746, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45747, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45748, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45749, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador')
;

-- ── PASSO 3: Inserir 108 resultados herpetofauna ──
INSERT INTO resultados_herpetofauna (id_esforco, id_especie, numero_de_individuos, tipo_amostragem, observacoes)
VALUES
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45722 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana albopunctata' LIMIT 1), 4, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45722 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana polytaenia' LIMIT 1), 5, 'Visualização,Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45722 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Dendropsophus minutus' LIMIT 1), 1, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45722 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Ololygon carnevallii' LIMIT 1), 4, 'Visualização,Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45722 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Thoropa miliaris' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45723 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana albopunctata' LIMIT 1), 10, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45723 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana faber' LIMIT 1), 15, 'Visualização,Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45723 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Dendropsophus branneri' LIMIT 1), 8, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45723 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Dendropsophus decipiens' LIMIT 1), 2, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45723 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Dendropsophus elegans' LIMIT 1), 5, 'Visualização,Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45723 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Dendropsophus minutus' LIMIT 1), 10, 'Visualização,Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45723 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Leptodactylus fuscus' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45723 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Leptodactylus luctator' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45723 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Leptodactylus mystacinus' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45723 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Rhinella crucifer' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45724 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana albopunctata' LIMIT 1), 0, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45724 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana polytaenia' LIMIT 1), 4, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45724 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Dendropsophus branneri' LIMIT 1), 4, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45724 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Scinax crospedospilus' LIMIT 1), 7, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45725 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana albopunctata' LIMIT 1), 6, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45725 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana polytaenia' LIMIT 1), 2, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45726 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana albopunctata' LIMIT 1), 8, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45726 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Dendropsophus branneri' LIMIT 1), 5, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45726 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Dendropsophus minutus' LIMIT 1), 6, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45726 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Physalaemus cuvieri' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45726 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Scinax crospedospilus' LIMIT 1), 13, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45727 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana polytaenia' LIMIT 1), 3, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45728 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana albopunctata' LIMIT 1), 5, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45728 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Scinax aff. perereca' LIMIT 1), 5, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45728 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Scinax fuscovarius' LIMIT 1), 3, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45712 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Pitfall' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Rhinella crucifer' LIMIT 1), 1, 'Captura', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45712 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Pitfall' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Thoropa miliaris' LIMIT 1), 2, 'Captura', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45713 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Pitfall' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Rhinella crucifer' LIMIT 1), 1, 'Captura', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45736 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana faber' LIMIT 1), 4, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45736 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Crotalus durissus' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45736 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Dendropsophus branneri' LIMIT 1), 5, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45736 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Dendropsophus elegans' LIMIT 1), 5, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45736 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Dendropsophus minutus' LIMIT 1), 7, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45737 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana albopunctata' LIMIT 1), 5, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45737 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Dendropsophus branneri' LIMIT 1), 8, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45738 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Dendropsophus branneri' LIMIT 1), 7, 'Visualização,Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45738 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Dendropsophus elegans' LIMIT 1), 5, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45738 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Dendropsophus minutus' LIMIT 1), 4, 'Visualização,Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45738 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Leptodactylus luctator' LIMIT 1), 8, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45739 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Ololygon carnevallii' LIMIT 1), 1, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45740 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Ololygon carnevallii' LIMIT 1), 2, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45741 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Thoropa miliaris' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45741 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Tropidurus gr. torquatus' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45742 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana albopunctata' LIMIT 1), 2, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45742 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Dendropsophus elegans' LIMIT 1), 2, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45742 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Dendropsophus minutus' LIMIT 1), 3, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45742 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Leptodactylus luctator' LIMIT 1), 3, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45742 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Rhinella crucifer' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45742 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Scinax fuscovarius' LIMIT 1), 3, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45742 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Thoropa miliaris' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45716 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Pitfall' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Physalaemus cuvieri' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45716 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Pitfall' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Rhinella crucifer' LIMIT 1), 2, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45729 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Amphisbaena alba' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45729 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Hylodes cf. uai' LIMIT 1), 2, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45729 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Hylodes cf. uai' LIMIT 1), 1, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45732 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana albopunctata' LIMIT 1), 3, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45732 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana pardalis' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45732 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana polytaenia' LIMIT 1), 2, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45732 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Ololygon carnevallii' LIMIT 1), 2, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45733 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana albopunctata' LIMIT 1), 5, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45733 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana polytaenia' LIMIT 1), 3, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45733 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Leptodactylus labyrinthicus' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45733 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Leptodactylus luctator' LIMIT 1), 2, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45733 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Rhinella crucifer' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45734 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Ololygon carnevallii' LIMIT 1), 2, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45734 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Thoropa miliaris' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45735 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana albopunctata' LIMIT 1), 3, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45714 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Pitfall' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Amerotyphlops brongersmianus' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45714 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Pitfall' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Rhinella crucifer' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45715 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Pitfall' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Rhinella crucifer' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45750 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana faber' LIMIT 1), 6, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45750 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana polytaenia' LIMIT 1), 5, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45751 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana faber' LIMIT 1), 6, 'Visualização,Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45751 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana polytaenia' LIMIT 1), 3, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45751 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Dendropsophus minutus' LIMIT 1), 5, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45751 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Ololygon carnevallii' LIMIT 1), 2, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45751 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Rhinella granulosa' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45752 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Haddadus binotatus' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45753 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana faber' LIMIT 1), 2, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45753 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Ololygon carnevallii' LIMIT 1), 4, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45754 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Dendropsophus minutus' LIMIT 1), 4, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45754 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Ololygon carnevallii' LIMIT 1), 6, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45755 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Ololygon carnevallii' LIMIT 1), 5, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45756 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana faber' LIMIT 1), 3, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45756 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana polytaenia' LIMIT 1), 5, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45756 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Crotalus durissus' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45720 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Pitfall' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Rhinella crucifer' LIMIT 1), 3, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45720 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Pitfall' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Thoropa miliaris' LIMIT 1), 2, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45721 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Pitfall' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Erythrolamprus typhlus' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45753 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana polytaenia' LIMIT 1), 2, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45743 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Ololygon carnevallii' LIMIT 1), 1, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45744 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Enyalius bilineatus' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45746 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana albopunctata' LIMIT 1), 2, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45746 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Crotalus durissus' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45746 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Leptodactylus luctator' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45747 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Dendropsophus branneri' LIMIT 1), 3, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45747 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Dendropsophus minutus' LIMIT 1), 3, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45747 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Leptodactylus mystacinus' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45747 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Ololygon carnevallii' LIMIT 1), 2, 'Visualização,Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45748 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Rhinella granulosa' LIMIT 1), 3, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45749 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Boana albopunctata' LIMIT 1), 3, 'Vocalização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45749 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Busca Ativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Leptodactylus luctator' LIMIT 1), 1, 'Visualização', NULL),
  ((SELECT id_esforco FROM esforcos_amostragem WHERE id_ponto_coleta=45718 AND grupo_biologico='Herpetofauna' AND metodo_de_captura='Pitfall' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico='Thoropa miliaris' LIMIT 1), 1, 'Visualização', NULL)
;

-- ── Validação pós-migração ──
SELECT COUNT(*) AS esforcos FROM esforcos_amostragem ea
  JOIN pontos_coleta pc ON ea.id_ponto_coleta=pc.id_ponto_coleta
  WHERE pc.id_projeto=165 AND ea.grupo_biologico='Herpetofauna';

SELECT COUNT(*) AS resultados FROM resultados_herpetofauna rh
  JOIN esforcos_amostragem ea ON rh.id_esforco=ea.id_esforco
  JOIN pontos_coleta pc ON ea.id_ponto_coleta=pc.id_ponto_coleta
  WHERE pc.id_projeto=165;