INSERT INTO esforcos_amostragem (id_ponto_coleta, grupo_biologico, metodo_de_captura, tipo_de_amostragem, esforco, unidade_esforco)
VALUES
  (45712, 'Herpetofauna', 'Pitfall', 'Quantitativa', 60.0, 'baldes/noite'),
  (45722, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45723, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45724, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45725, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45726, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45727, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45728, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45714, 'Herpetofauna', 'Pitfall', 'Quantitativa', 60.0, 'baldes/noite'),
  (45715, 'Herpetofauna', 'Pitfall', 'Quantitativa', 60.0, 'baldes/noite'),
  (45729, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45730, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45731, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45732, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45733, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45734, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45735, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45716, 'Herpetofauna', 'Pitfall', 'Quantitativa', 60.0, 'baldes/noite'),
  (45717, 'Herpetofauna', 'Pitfall', 'Quantitativa', 60.0, 'baldes/noite'),
  (45736, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45737, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45738, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45739, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45740, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45741, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45742, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45720, 'Herpetofauna', 'Pitfall', 'Quantitativa', 60.0, 'baldes/noite'),
  (45721, 'Herpetofauna', 'Pitfall', 'Quantitativa', 60.0, 'baldes/noite'),
  (45750, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45751, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45752, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45753, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45754, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45755, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45756, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45718, 'Herpetofauna', 'Pitfall', 'Quantitativa', 60.0, 'baldes/noite'),
  (45719, 'Herpetofauna', 'Pitfall', 'Quantitativa', 60.0, 'baldes/noite'),
  (45743, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45744, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45745, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45746, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45747, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45748, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador'),
  (45749, 'Herpetofauna', 'Busca Ativa', 'Quantitativa', 60.0, 'minutos/observador')
;