-- ============================================================
-- MIGRACAO ICTIOFAUNA - Projeto 165 (ITAGUA001)
-- Campanha: C028-2026-05-SC
-- 6 especies novas + 32 pontos + 34 esforcos + 62 resultados
-- ============================================================

-- PASSO 0: Inserir campanha do monitoramento
INSERT INTO campanhas (nome_campanha)
SELECT 'C028-2026-05-SC'
WHERE NOT EXISTS (SELECT 1 FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC');

-- PASSO 1: Inserir especies novas
INSERT INTO especies (nome_cientifico, grupo_biologico)
VALUES
  ('Delturus carinotus', 'Ictiofauna'),
  ('Geophagus', 'Ictiofauna'),
  ('Hypomasticus copelandii', 'Ictiofauna'),
  ('Hypomasticus mormyrops', 'Ictiofauna'),
  ('Hypostomus affinis', 'Ictiofauna'),
  ('Phalloceros cf. uai', 'Ictiofauna')
ON CONFLICT (nome_cientifico) DO NOTHING;

-- PASSO 1.5: Limpeza controlada para reexecucao da carga de ictio
WITH pontos_alvo AS (
  SELECT pc.id_ponto_coleta
  FROM pontos_coleta pc
  JOIN campanhas c ON c.id_campanha = pc.id_campanha
  WHERE pc.id_projeto = 165
    AND c.nome_campanha = 'C028-2026-05-SC'
    AND pc.nome_ponto IN ('RPDGN0', 'RPDGN1', 'RPDGN2', 'RPDGN3', 'RPFOR1', 'RPFOR2', 'RPFOR3', 'RPJAC1', 'RPJAC2', 'RPJAC3', 'RPJAC4', 'RPJAC5', 'RPSPT1', 'RPSPT2', 'RPSPT3', 'RPSPT4', 'RPSPT5', 'TRDGN1', 'TRDGN2', 'TRDGN3', 'TRFOR1', 'TRFOR2', 'TRFOR3', 'TRFOR4', 'TRFOR5', 'TRJAC1', 'TRJAC2', 'TRJAC3', 'TRJAC4', 'TRSPT1', 'TRSPT2', 'TRSPT3')
)
DELETE FROM resultados_ictiofauna ri
WHERE ri.id_esforco IN (
  SELECT ea.id_esforco
  FROM esforcos_amostragem ea
  WHERE ea.grupo_biologico = 'Ictiofauna'
    AND ea.id_ponto_coleta IN (SELECT id_ponto_coleta FROM pontos_alvo)
);
WITH pontos_alvo AS (
  SELECT pc.id_ponto_coleta
  FROM pontos_coleta pc
  JOIN campanhas c ON c.id_campanha = pc.id_campanha
  WHERE pc.id_projeto = 165
    AND c.nome_campanha = 'C028-2026-05-SC'
    AND pc.nome_ponto IN ('RPDGN0', 'RPDGN1', 'RPDGN2', 'RPDGN3', 'RPFOR1', 'RPFOR2', 'RPFOR3', 'RPJAC1', 'RPJAC2', 'RPJAC3', 'RPJAC4', 'RPJAC5', 'RPSPT1', 'RPSPT2', 'RPSPT3', 'RPSPT4', 'RPSPT5', 'TRDGN1', 'TRDGN2', 'TRDGN3', 'TRFOR1', 'TRFOR2', 'TRFOR3', 'TRFOR4', 'TRFOR5', 'TRJAC1', 'TRJAC2', 'TRJAC3', 'TRJAC4', 'TRSPT1', 'TRSPT2', 'TRSPT3')
)
DELETE FROM esforcos_amostragem ea
WHERE ea.grupo_biologico = 'Ictiofauna'
  AND ea.id_ponto_coleta IN (SELECT id_ponto_coleta FROM pontos_alvo);
WITH pontos_alvo AS (
  SELECT pc.id_ponto_coleta
  FROM pontos_coleta pc
  JOIN campanhas c ON c.id_campanha = pc.id_campanha
  WHERE pc.id_projeto = 165
    AND c.nome_campanha = 'C028-2026-05-SC'
    AND pc.nome_ponto IN ('RPDGN0', 'RPDGN1', 'RPDGN2', 'RPDGN3', 'RPFOR1', 'RPFOR2', 'RPFOR3', 'RPJAC1', 'RPJAC2', 'RPJAC3', 'RPJAC4', 'RPJAC5', 'RPSPT1', 'RPSPT2', 'RPSPT3', 'RPSPT4', 'RPSPT5', 'TRDGN1', 'TRDGN2', 'TRDGN3', 'TRFOR1', 'TRFOR2', 'TRFOR3', 'TRFOR4', 'TRFOR5', 'TRJAC1', 'TRJAC2', 'TRJAC3', 'TRJAC4', 'TRSPT1', 'TRSPT2', 'TRSPT3')
)
DELETE FROM pontos_coleta pc
WHERE pc.id_ponto_coleta IN (SELECT id_ponto_coleta FROM pontos_alvo)
  AND NOT EXISTS (
    SELECT 1 FROM esforcos_amostragem ea WHERE ea.id_ponto_coleta = pc.id_ponto_coleta
  );

-- PASSO 2: Inserir pontos da campanha C028-2026-05-SC
INSERT INTO pontos_coleta (id_projeto, id_campanha, data_hora_coleta, nome_ponto, latitude, longitude, bacia_hidrografica, observacoes)
VALUES
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'RPDGN0', -19.071735, -42.871966, 'Bacia do rio Doce', 'curso_d_agua=Guanhães | municipio=Dores de Guanhães'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'RPDGN1', -19.076922, -42.876023, 'Bacia do rio Doce', 'curso_d_agua=Guanhães | municipio=Dores de Guanhães'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'RPDGN2', -19.06144, -42.882376, 'Bacia do rio Doce', 'curso_d_agua=Guanhães | municipio=Dores de Guanhães'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'RPDGN3', -19.045036, -42.894125, 'Bacia do rio Doce', 'curso_d_agua=Guanhães | municipio=Dores de Guanhães'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'RPFOR1', -18.891613, -42.695491, 'Bacia do rio Doce', 'curso_d_agua=Corrente Grande | municipio=Virginópolis'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'RPFOR2', -18.897835, -42.707135, 'Bacia do rio Doce', 'curso_d_agua=Corrente Grande | municipio=Virginópolis'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'RPFOR3', -18.897185, -42.683107, 'Bacia do rio Doce', 'curso_d_agua=Corrente Grande | municipio=Virginópolis'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'RPJAC1', -18.988329, -42.963673, 'Bacia do rio Doce', 'curso_d_agua=Guanhães | municipio=Dores de Guanhães'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'RPJAC2', -18.993817, -42.960833, 'Bacia do rio Doce', 'curso_d_agua=Guanhães | municipio=Dores de Guanhães'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'RPJAC3', -18.995343, -42.956646, 'Bacia do rio Doce', 'curso_d_agua=Guanhães | municipio=Dores de Guanhães'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'RPJAC4', -18.91604, -43.076668, 'Bacia do rio Doce', 'curso_d_agua=Guanhães | municipio=Dores de Guanhães'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'RPJAC5', -19.006454, -42.942056, 'Bacia do rio Doce', 'curso_d_agua=Guanhães | municipio=Dores de Guanhães'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'RPSPT1', -19.045455, -42.893701, 'Bacia do rio Doce', 'curso_d_agua=Guanhães | municipio=Dores de Guanhães'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'RPSPT2', -19.048547, -42.925845, 'Bacia do rio Doce', 'curso_d_agua=Guanhães | municipio=Dores de Guanhães'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'RPSPT3', -19.039039, -42.924529, 'Bacia do rio Doce', 'curso_d_agua=Guanhães | municipio=Dores de Guanhães'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'RPSPT4', -19.006454, -42.942056, 'Bacia do rio Doce', 'curso_d_agua=Guanhães | municipio=Dores de Guanhães'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'RPSPT5', -18.992359, -42.953976, 'Bacia do rio Doce', 'curso_d_agua=Guanhães | municipio=Dores de Guanhães'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'TRDGN1', -19.061436, -42.906514, 'Bacia do rio Doce', 'curso_d_agua=Tributário | municipio=Dores de Guanhães'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'TRDGN2', -19.049786, -42.888739, 'Bacia do rio Doce', 'curso_d_agua=Tributário | municipio=Dores de Guanhães'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'TRDGN3', -19.064318, -42.890737, 'Bacia do rio Doce', 'curso_d_agua=Tributário | municipio=Dores de Guanhães'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'TRFOR1', -18.897322, -42.69416, 'Bacia do rio Doce', 'curso_d_agua=Tributário | municipio=Virginópolis'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'TRFOR2', -18.894973, -42.756034, 'Bacia do rio Doce', 'curso_d_agua=Tributário | municipio=Virginópolis'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'TRFOR3', -18.89503, -42.736144, 'Bacia do rio Doce', 'curso_d_agua=Tributário | municipio=Virginópolis'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'TRFOR4', -18.900099, -42.714961, 'Bacia do rio Doce', 'curso_d_agua=Tributário | municipio=Virginópolis'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'TRFOR5', -18.899056, -42.707261, 'Bacia do rio Doce', 'curso_d_agua=Tributário | municipio=Virginópolis'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'TRJAC1', -18.899056, -42.707261, 'Bacia do rio Doce', 'curso_d_agua=Tributário | municipio=Dores de Guanhães'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'TRJAC2', -18.994017, -42.963375, 'Bacia do rio Doce', 'curso_d_agua=Tributário | municipio=Dores de Guanhães'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'TRJAC3', -18.978485, -42.953993, 'Bacia do rio Doce', 'curso_d_agua=Tributário | municipio=Dores de Guanhães'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'TRJAC4', -18.970316, -42.957853, 'Bacia do rio Doce', 'curso_d_agua=Tributário | municipio=Dores de Guanhães'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'TRSPT1', -18.970316, -42.957853, 'Bacia do rio Doce', 'curso_d_agua=Tributário | municipio=Dores de Guanhães'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'TRSPT2', -18.970316, -42.957853, 'Bacia do rio Doce', 'curso_d_agua=Tributário | municipio=Dores de Guanhães'),
  (165, (SELECT id_campanha FROM campanhas WHERE nome_campanha = 'C028-2026-05-SC' LIMIT 1), '2026-05-01', 'TRSPT3', -18.970316, -42.957853, 'Bacia do rio Doce', 'curso_d_agua=Tributário | municipio=Dores de Guanhães')
;

-- PASSO 3: Inserir esforcos de amostragem
INSERT INTO esforcos_amostragem (id_ponto_coleta, grupo_biologico, metodo_de_captura, tipo_de_amostragem, esforco, unidade_esforco)
VALUES
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPDGN0' LIMIT 1), 'Ictiofauna', 'Rede de Emalhar', 'Quantitativa', 120.0, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPDGN1' LIMIT 1), 'Ictiofauna', 'Rede de Emalhar', 'Quantitativa', 120.0, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPDGN2' LIMIT 1), 'Ictiofauna', 'Rede de Emalhar', 'Quantitativa', 120.0, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPDGN3' LIMIT 1), 'Ictiofauna', 'Rede de Emalhar', 'Quantitativa', 120.0, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR1' LIMIT 1), 'Ictiofauna', 'Arrasto e peneira', 'Quantitativa', NULL, NULL),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR1' LIMIT 1), 'Ictiofauna', 'Rede de Emalhar', 'Quantitativa', 120.0, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR2' LIMIT 1), 'Ictiofauna', 'Arrasto e peneira', 'Quantitativa', NULL, NULL),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR2' LIMIT 1), 'Ictiofauna', 'Rede de Emalhar', 'Quantitativa', 120.0, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR3' LIMIT 1), 'Ictiofauna', 'Rede de Emalhar', 'Quantitativa', 120.0, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPJAC1' LIMIT 1), 'Ictiofauna', 'Rede de Emalhar', 'Quantitativa', 120.0, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPJAC2' LIMIT 1), 'Ictiofauna', 'Rede de Emalhar', 'Quantitativa', 120.0, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPJAC3' LIMIT 1), 'Ictiofauna', 'Rede de Emalhar', 'Quantitativa', 120.0, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPJAC4' LIMIT 1), 'Ictiofauna', 'Rede de Emalhar', 'Quantitativa', 120.0, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPJAC5' LIMIT 1), 'Ictiofauna', 'Rede de Emalhar', 'Quantitativa', 120.0, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPSPT1' LIMIT 1), 'Ictiofauna', 'Rede de Emalhar', 'Quantitativa', 120.0, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPSPT2' LIMIT 1), 'Ictiofauna', 'Rede de Emalhar', 'Quantitativa', 120.0, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPSPT3' LIMIT 1), 'Ictiofauna', 'Rede de Emalhar', 'Quantitativa', 120.0, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPSPT4' LIMIT 1), 'Ictiofauna', 'Rede de Emalhar', 'Quantitativa', 120.0, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPSPT5' LIMIT 1), 'Ictiofauna', 'Rede de Emalhar', 'Quantitativa', 120.0, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'TRDGN1' LIMIT 1), 'Ictiofauna', 'Arrasto e peneira', 'Qualitativa', NULL, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'TRDGN2' LIMIT 1), 'Ictiofauna', 'Arrasto e peneira', 'Qualitativa', NULL, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'TRDGN3' LIMIT 1), 'Ictiofauna', 'Arrasto e peneira', 'Qualitativa', NULL, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'TRFOR1' LIMIT 1), 'Ictiofauna', 'Arrasto e peneira', 'Qualitativa', NULL, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'TRFOR2' LIMIT 1), 'Ictiofauna', 'Arrasto e peneira', 'Qualitativa', NULL, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'TRFOR3' LIMIT 1), 'Ictiofauna', 'Arrasto e peneira', 'Qualitativa', NULL, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'TRFOR4' LIMIT 1), 'Ictiofauna', 'Arrasto e peneira', 'Qualitativa', NULL, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'TRFOR5' LIMIT 1), 'Ictiofauna', 'Arrasto e peneira', 'Qualitativa', NULL, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'TRJAC1' LIMIT 1), 'Ictiofauna', 'Arrasto e peneira', 'Qualitativa', NULL, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'TRJAC2' LIMIT 1), 'Ictiofauna', 'Arrasto e peneira', 'Qualitativa', NULL, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'TRJAC3' LIMIT 1), 'Ictiofauna', 'Arrasto e peneira', 'Qualitativa', NULL, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'TRJAC4' LIMIT 1), 'Ictiofauna', 'Arrasto e peneira', 'Qualitativa', NULL, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'TRSPT1' LIMIT 1), 'Ictiofauna', 'Arrasto e peneira', 'Qualitativa', NULL, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'TRSPT2' LIMIT 1), 'Ictiofauna', 'Arrasto e peneira', 'Qualitativa', NULL, 'm²/100'),
  ((SELECT pc.id_ponto_coleta FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'TRSPT3' LIMIT 1), 'Ictiofauna', 'Arrasto e peneira', 'Qualitativa', NULL, 'm²/100')
;

-- PASSO 4: Inserir resultados ictiofauna validos (linhas sem especie foram tratadas como ausencia de captura e permanecem apenas no esforco)
INSERT INTO resultados_ictiofauna (id_esforco, id_especie, numero_de_individuos, ct_cm, cp_cm, pc_g, sexo, emg, observacao_individuo_lote, tipo_amostragem)
VALUES
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'TRFOR3' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Arrasto e peneira' AND ea.tipo_de_amostragem = 'Qualitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Astyanax lacustris' LIMIT 1), 5, 4.5, 4.0, 0.01, NULL, NULL, NULL, 'Qualitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'TRFOR3' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Arrasto e peneira' AND ea.tipo_de_amostragem = 'Qualitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Poecilia reticulata' LIMIT 1), 6, 5.0, 4.6, 0.02, NULL, NULL, NULL, 'Qualitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'TRFOR3' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Arrasto e peneira' AND ea.tipo_de_amostragem = 'Qualitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Phalloceros cf. uai' LIMIT 1), 8, 5.0, 4.0, 0.03, NULL, NULL, NULL, 'Qualitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'TRFOR4' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Arrasto e peneira' AND ea.tipo_de_amostragem = 'Qualitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Knodus moenkhausii' LIMIT 1), 4, 5.0, 4.7, 0.03, NULL, NULL, NULL, 'Qualitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'TRFOR4' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Arrasto e peneira' AND ea.tipo_de_amostragem = 'Qualitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hasemania nana' LIMIT 1), 6, 5.0, 4.7, 0.03, NULL, NULL, NULL, 'Qualitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'TRFOR4' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Arrasto e peneira' AND ea.tipo_de_amostragem = 'Qualitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Phalloceros cf. uai' LIMIT 1), 3, 5.0, 4.5, 0.04, NULL, NULL, NULL, 'Qualitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR1' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Arrasto e peneira' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hasemania nana' LIMIT 1), 16, 5.0, 4.7, 0.03, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR1' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Arrasto e peneira' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Phalloceros cf. uai' LIMIT 1), 12, 5.0, 4.5, 0.04, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR1' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Arrasto e peneira' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Knodus moenkhausii' LIMIT 1), 4, 5.0, 4.7, 0.03, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR2' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Arrasto e peneira' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Phalloceros cf. uai' LIMIT 1), 6, 5.0, 4.5, 0.04, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR2' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Arrasto e peneira' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Knodus moenkhausii' LIMIT 1), 4, 5.0, 4.7, 0.03, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR3' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Geophagus brasiliensis' LIMIT 1), 3, 14.0, 11.5, 23.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR3' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Rhamdia quelen' LIMIT 1), 1, 26.0, 22.0, 189.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR3' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hoplias intermedius' LIMIT 1), 1, 32.5, 28.0, 490.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR3' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Rhamdia quelen' LIMIT 1), 1, 28.0, 24.0, 203.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR3' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hoplias intermedius' LIMIT 1), 1, 41.0, 35.0, 735.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR3' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hypostomus affinis' LIMIT 1), 1, 19.0, 15.0, 71.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR3' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hypostomus affinis' LIMIT 1), 1, 26.0, 21.0, 130.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR3' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hypostomus affinis' LIMIT 1), 1, 19.0, 15.0, 79.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR3' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hypostomus affinis' LIMIT 1), 1, 25.0, 21.0, 128.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR3' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hypostomus affinis' LIMIT 1), 1, 25.0, 21.0, 133.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR3' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hypostomus affinis' LIMIT 1), 1, 25.0, 21.0, 129.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR3' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hypostomus affinis' LIMIT 1), 1, 20.0, 16.5, 86.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR3' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hypostomus affinis' LIMIT 1), 1, 20.0, 16.5, 92.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR3' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hypostomus affinis' LIMIT 1), 1, 25.0, 21.0, 133.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR3' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hypostomus affinis' LIMIT 1), 1, 33.0, 28.0, 262.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR3' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hypostomus affinis' LIMIT 1), 1, 29.0, 22.0, 238.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR3' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hypostomus affinis' LIMIT 1), 1, 23.0, 20.0, 126.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR3' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hypostomus affinis' LIMIT 1), 1, 24.0, 19.0, 131.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR3' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Geophagus' LIMIT 1), 12, 9.0, 7.0, 12.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR1' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Geophagus' LIMIT 1), 6, 9.0, 7.0, 12.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR1' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Astyanax lacustris' LIMIT 1), 8, 8.0, 6.0, 9.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR1' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hoplias malabaricus' LIMIT 1), 1, 14.5, 12.0, 20.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR2' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hypostomus affinis' LIMIT 1), 1, 23.0, 20.0, 93.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPFOR2' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hoplias intermedius' LIMIT 1), 1, 26.0, 23.4, 265.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPJAC3' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hypomasticus mormyrops' LIMIT 1), 1, 21.0, 18.0, 230.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPJAC3' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hypomasticus mormyrops' LIMIT 1), 1, 27.0, 24.0, 256.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPJAC3' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Astyanax lacustris' LIMIT 1), 6, 9.0, 7.5, 10.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPJAC3' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hoplias malabaricus' LIMIT 1), 1, 31.0, 26.5, 345.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPJAC5' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hypomasticus copelandii' LIMIT 1), 1, 31.5, 27.0, 286.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPJAC5' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hoplias intermedius' LIMIT 1), 1, 42.0, 36.5, 389.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPJAC5' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hoplias malabaricus' LIMIT 1), 1, 32.0, 28.0, 357.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPJAC5' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hoplias malabaricus' LIMIT 1), 1, 40.0, 34.0, 680.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPJAC5' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Astyanax lacustris' LIMIT 1), 7, 9.0, 7.5, 10.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPSPT5' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hypomasticus mormyrops' LIMIT 1), 1, 21.0, 18.0, 230.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPSPT5' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hypomasticus mormyrops' LIMIT 1), 1, 27.0, 24.0, 256.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPSPT5' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Astyanax lacustris' LIMIT 1), 6, 9.0, 7.5, 10.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPSPT5' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hoplias malabaricus' LIMIT 1), 1, 31.0, 26.5, 345.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPSPT4' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hypomasticus copelandii' LIMIT 1), 1, 31.5, 27.0, 286.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPSPT4' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hoplias intermedius' LIMIT 1), 1, 42.0, 36.5, 389.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPSPT4' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hoplias malabaricus' LIMIT 1), 1, 32.0, 28.0, 357.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPSPT4' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hoplias malabaricus' LIMIT 1), 1, 40.0, 34.0, 680.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPSPT4' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Astyanax lacustris' LIMIT 1), 7, 9.0, 7.5, 10.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPJAC4' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Astyanax lacustris' LIMIT 1), 2, 13.5, 11.0, 44.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPJAC4' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hoplias intermedius' LIMIT 1), 1, 39.0, 33.0, 650.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPJAC4' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hypostomus affinis' LIMIT 1), 3, 38.0, 33.0, 268.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPJAC4' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hypostomus affinis' LIMIT 1), 4, 19.0, 15.0, 76.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPJAC4' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Hypostomus affinis' LIMIT 1), 4, 29.0, 22.0, 228.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPJAC4' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Delturus carinotus' LIMIT 1), 3, 26.0, 21.0, 209.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPJAC4' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Delturus carinotus' LIMIT 1), 3, 19.0, 17.0, 81.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPJAC4' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Delturus carinotus' LIMIT 1), 2, 24.5, 21.0, 150.0, NULL, NULL, NULL, 'Quantitativa'),
  ((SELECT ea.id_esforco FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND pc.nome_ponto = 'RPJAC4' AND ea.grupo_biologico = 'Ictiofauna' AND ea.metodo_de_captura = 'Rede de Emalhar' AND ea.tipo_de_amostragem = 'Quantitativa' LIMIT 1), (SELECT id_especie FROM especies WHERE nome_cientifico = 'Delturus carinotus' LIMIT 1), 1, 26.8, 22.0, 211.0, NULL, NULL, NULL, 'Quantitativa')
;

-- VALIDACAO POS-MIGRACAO
SELECT COUNT(*) AS n_pontos FROM pontos_coleta pc JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC';
SELECT COUNT(*) AS n_esforcos FROM esforcos_amostragem ea JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC' AND ea.grupo_biologico = 'Ictiofauna';
SELECT COUNT(*) AS n_resultados FROM resultados_ictiofauna ri JOIN esforcos_amostragem ea ON ea.id_esforco = ri.id_esforco JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC';
SELECT COUNT(DISTINCT e.nome_cientifico) AS n_especies FROM resultados_ictiofauna ri JOIN esforcos_amostragem ea ON ea.id_esforco = ri.id_esforco JOIN pontos_coleta pc ON pc.id_ponto_coleta = ea.id_ponto_coleta JOIN campanhas c ON c.id_campanha = pc.id_campanha JOIN especies e ON e.id_especie = ri.id_especie WHERE pc.id_projeto = 165 AND c.nome_campanha = 'C028-2026-05-SC';